package com.example.pancakemusicbox.model

// AudioQuality는 별도 파일로 분리됨 (AudioQuality.kt)

/**
 * 앨범 정보를 담는 클래스
 * Java 코드와의 호환성을 위해 필드와 getter 패턴 사용
 */
class Album {
    private val _id: String
    private val _title: String
    private val _artist: String
    private val _artworkUri: String
    private val _year: Int?
    private val _tracks: List<Track>
    private val _genre: String?

    constructor(
        id: String,
        title: String,
        artist: String,
        artworkUri: String,
        year: Int? = null,
        tracks: List<Track> = emptyList(),
        genre: String? = null
    ) {
        this._id = id
        this._title = title
        this._artist = artist
        this._artworkUri = artworkUri
        this._year = year
        this._tracks = tracks
        this._genre = genre
    }

    // Getter 메서드
    fun getId(): String = _id
    fun getTitle(): String = _title
    fun getArtist(): String = _artist
    fun getArtworkUri(): String = _artworkUri
    fun getYear(): Int? = _year
    fun getTracks(): List<Track> = _tracks
    fun getGenre(): String? = _genre
    
    // 편의 메서드
    fun getTrackCount(): Int = _tracks.size

    // 데이터 클래스와 같은 기능 제공을 위한 메서드들
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is Album) return false

        return _id == other._id &&
                _title == other._title &&
                _artist == other._artist &&
                _artworkUri == other._artworkUri &&
                _year == other._year &&
                _tracks == other._tracks &&
                _genre == other._genre
    }

    override fun hashCode(): Int {
        var result = _id.hashCode()
        result = 31 * result + _title.hashCode()
        result = 31 * result + _artist.hashCode()
        result = 31 * result + _artworkUri.hashCode()
        result = 31 * result + (_year ?: 0)
        result = 31 * result + _tracks.hashCode()
        result = 31 * result + (_genre?.hashCode() ?: 0)
        return result
    }

    override fun toString(): String {
        return "Album(id='$_id', title='$_title', artist='$_artist', artworkUri='$_artworkUri', " +
                "year=$_year, tracks=${_tracks.size}, genre=$_genre)"
    }
}

/**
 * 플레이리스트 정보를 담는 클래스
 * Java 코드와의 호환성을 위해 필드와 getter 패턴 사용
 */
class Playlist {
    private val _id: String
    private val _name: String
    private val _tracks: List<Track>
    private val _createdAt: Long
    private val _isAutoGenerated: Boolean

    constructor(
        id: String,
        name: String,
        tracks: List<Track> = emptyList(),
        createdAt: Long,
        isAutoGenerated: Boolean = false
    ) {
        this._id = id
        this._name = name
        this._tracks = tracks
        this._createdAt = createdAt
        this._isAutoGenerated = isAutoGenerated
    }

    // Getter 메서드
    fun getId(): String = _id
    fun getName(): String = _name
    fun getTracks(): List<Track> = _tracks
    fun getCreatedAt(): Long = _createdAt
    fun isAutoGenerated(): Boolean = _isAutoGenerated
    
    // 편의 메서드
    fun getTrackCount(): Int = _tracks.size
    
    // 대표 앨범 아트 URI 4개를 가져오는 함수
    fun getRepresentativeArtworks(maxCount: Int = 4): List<String> {
        return _tracks.asSequence()
            .distinctBy { it.getAlbumArtUri() }
            .take(maxCount)
            .map { it.getAlbumArtUri() }
            .toList()
    }

    // 데이터 클래스와 같은 기능 제공을 위한 메서드들
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is Playlist) return false

        return _id == other._id &&
                _name == other._name &&
                _tracks == other._tracks &&
                _createdAt == other._createdAt &&
                _isAutoGenerated == other._isAutoGenerated
    }

    override fun hashCode(): Int {
        var result = _id.hashCode()
        result = 31 * result + _name.hashCode()
        result = 31 * result + _tracks.hashCode()
        result = 31 * result + _createdAt.hashCode()
        result = 31 * result + _isAutoGenerated.hashCode()
        return result
    }

    override fun toString(): String {
        return "Playlist(id='$_id', name='$_name', tracks=${_tracks.size}, " +
                "createdAt=$_createdAt, isAutoGenerated=$_isAutoGenerated)"
    }
}